name: jmovies
description: JMovies

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.4
  intl: ^0.16.1
  http: ^0.12.1
  share: ^0.6.4+1
  timeago: ^2.0.26
  provider: ^4.1.0
  device_apps: ^1.0.9
  fluttertoast: ^4.0.1
  splashscreen: ^1.2.0
  path_provider: ^1.6.7
  auto_size_text: ^2.1.0
  carousel_slider: ^2.1.0
  android_intent: ^0.3.7+2
  shared_preferences: ^0.5.7+1
  json_serializable: ^3.3.0
  flutter_rating_bar: ^3.0.1+1
  cached_network_image: ^2.2.0+1
  youtube_player_flutter: ^6.1.1
  permission_handler: ^5.0.0+hotfix.5
  firebase_dynamic_links: ^0.5.0+11
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.11
  firebase_admob: ^0.9.3+2



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logos/logo.png
    - assets/images/logos/logo_transparent.png
    - assets/images/faq.jpeg
    - assets/images/help.png
    - assets/images/share.png
    - assets/images/support.png
    - assets/images/download.png
    - assets/images/placeholder.jpeg
    - assets/images/search_error.jpeg
    - assets/images/no_internet.jpeg
    - assets/images/youtube.png
    - assets/images/genres/adventure.jpeg
    - assets/images/genres/animation.jpeg
    - assets/images/genres/avengers_bg.jpeg
    - assets/images/genres/romance.jpeg
    - assets/images/genres/sci.jpeg
    - assets/images/genres/comedy.jpeg
    - assets/images/genres/crime.jpeg
    - assets/images/genres/fantasy.jpeg
    - assets/images/genres/horror.jpeg
    - assets/images/genres/war.jpeg
    - assets/images/genres/musical.jpeg
    - assets/images/genres/family.jpeg
    - assets/images/genres/documentary.jpeg
    - assets/images/genres/drama.jpeg
    - assets/images/genres/sports.jpeg
    - assets/images/genres/history.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bellota
      fonts:
        - asset: assets/fonts/Bellota-Bold.ttf
          weight: 900
        - asset: assets/fonts/Bellota-Regular.ttf
        - asset: assets/fonts/Bellota-BoldItalic.ttf
          style: italic
